### ISSUE TITLE
error 61 - connection refused  

### ISSUE THREAD

**Issue by alpceylan** [robotpy/pynetworktables#114]
I'm having this error and I can't connect to 127.0.0.1 because of this

`DEBUG:nt:client trying to connect`
`ERROR:nt:select() to 127.0.0.1 port 1735 error 61 - Connection refused`

**Comment by virtuald** [comment]
What are you trying to do?

**Comment by alpceylan** [comment]
I'm trying to start lime-plotter module which uses network tables

![Ekran Resmi 2020-10-08 00 30 49](https://user-images.githubusercontent.com/31375123/95390150-99804300-08fd-11eb-8bd0-97a5930ae728.png)

**Comment by alpceylan** [comment]
I'm trying to start lime-plotter module which uses network tables in my localhost

![Ekran Resmi 2020-10-08 00 30 49](https://user-images.githubusercontent.com/31375123/95390150-99804300-08fd-11eb-8bd0-97a5930ae728.png)

**Comment by virtuald** [comment]
What NetworkTables server are you running on your localhost? Robot, custom thing? What address does it say that it's listening on?

You might try connecting to 'localhost' instead of 127.0.0.1. You can also try your external address?

**Comment by alpceylan** [comment]
It's python network tables server. I specify which ip address it should work on, however since i'm working on my personal computer i can only connect to 127.0.0.1.

If I type localhost nothing changes it still try to connect 127.0.0.1

**Comment by virtuald** [comment]
Are you sure the server is actually running? Maybe your firewall is blocking it? Are there any errors in the logging output for the server?

**Comment by alpceylan** [comment]
I was able to use module before so I'm sure it's running. And I'm sure firewall isn't blocking I tried to run a node.js project in 1735 port and it worked just fine.

I don't know how to check logging output, can you tell me?

**Comment by virtuald** [comment]
See the information in the troubleshooting guide: https://robotpy.readthedocs.io/en/stable/troubleshooting.html#problem-i-can-t-determine-if-networktables-has-connected.

Have you tried connecting to OutlineViewer in server mode?

**Comment by alpceylan** [comment]
Let me try thanks

**Comment by virtuald** [comment]
Did you figure this out?

**Comment by alpceylan** [comment]
I'm still trying, I will close this issue when I solved my problem.

**Comment by alpceylan** [comment]
error fixed

**Comment by virtuald** [comment]
What ended up being the problem? We can update the troubleshooting docs to help out someone who has this problem in the future.

**Comment by alpceylan** [comment]
it is about java version

**Comment by alpceylan** [comment]
it is because of my computer's problems not about the package
