### ISSUE TITLE
Using shuffleboard widgets?

### ISSUE THREAD

**Issue by superfast852** [robotpy/pynetworktables#123]
I'm using pynetworktables for my own project outside of FRC, and I'd like to display my robot's individual wheel speeds using the Mecanum Drive base widget, but i can't seem to find a way to use the widgets. I can successfully post data on NetworkTables and they show up on Shuffleboard, but nowhere in the documentation does it say how to use the widgets. Any help?

**Comment by virtuald** [comment]
I don't know the answer to this either. I recommend asking on ChiefDelphi, someone is likely to know.
