### ISSUE TITLE
Add remove listener

### ISSUE THREAD

**Issue by SkyZH** [robotpy/pynetworktables#28]
For example, `removeWsConnectionListener`, `removeRobotConnectionListener`, to introduce full event features.

**Comment by virtuald** [comment]
These already exist for pynetworktables ([see here](https://github.com/robotpy/pynetworktables/blob/master/networktables/networktable.py#L634)). Perhaps you meant to file that bug report on pynetworktables2js?

**Comment by SkyZH** [comment]
Sorry for submitting issues in wrong place.
