### ISSUE TITLE
Implement 2017 driver station client connection support

### ISSUE THREAD

**Issue by virtuald** [robotpy/pynetworktables#35]
As implemented in https://github.com/wpilibsuite/ntcore/commit/77edf1e103aff250d9e83d447b357064c8b2c988

**Comment by auscompgeek** [comment]
If anyone wants to have a crack at this, I have a WIP at https://github.com/auscompgeek/pynetworktables/tree/dsclient.

**Comment by virtuald** [comment]
Whoever does it should replace/remove dashboard.py, as it's obsolete.

**Comment by auscompgeek** [comment]
Figured I'd have another crack at this.
