### ISSUE TITLE
Does not print "Disconnected" when robot disconnects

### ISSUE THREAD

**Issue by calebeby** [robotpy/pynetworktables#40]
Hi Dustin,

First of all, thanks for this! I have found it really useful.

Here's the issue:

The robot connects, prints `CONNECTED`, `pynetworktables2js` sends value :white_check_mark:
The robot/network disconnects. Nothing happens :x:

Any idea why?

Thanks

**Comment by calebeby** [comment]
The above happens on Ubuntu, but the behavior is as expected on Windows.

**Comment by virtuald** [comment]
Interesting. So you're saying that pynetworktables2js doesn't send the event to the HTML page, and that nothing is showing up?

I'm curious if you see this issue just using the networktables examples.

**Comment by calebeby** [comment]
Correct. I'll check the examples when I get access to robotics computers
tomorrow.

**Comment by virtuald** [comment]
Assume this resolved itself? Closing.
