### ISSUE TITLE
NetworkTable.getBooleanArray() returns tuple, not list

### ISSUE THREAD

**Issue by ryannazaretian** [robotpy/pynetworktables#46]
Title sums it up.

```
>>> type(nt.getBooleanArray('LED'))
tuple 
```
Documentation says it should be this:
:rtype: list(bool)

**Comment by virtuald** [comment]
Docs are wrong, it should be a tuple.

**Comment by auscompgeek** [comment]
Same with the rest of the get*Array methods.

**Comment by virtuald** [comment]
I see that, I'm fixing it...
