### ISSUE TITLE
Sync code with 2018 updates

### ISSUE THREAD

**Issue by virtuald** [robotpy/pynetworktables#49]
This may be fairly involved, there are some updates to the way ntcore does synchronization. Additionally, they changed NT to have instances instead of lots of static globals -- but we do that anyways. Still, the code will need to be reviewed and updated.

**Comment by virtuald** [comment]
I'm going to start on this tonight and see how bad the updates are, as this is blocking pull requests over in robotpy-wpilib.

**Comment by auscompgeek** [comment]
Fixing #35 would probably be useful as well. Heck, there's a few other 2017 things that never landed here.

**Comment by virtuald** [comment]
Well, done for tonight. I updated the git-source-track information, and *most* of the changes seem to be pretty minimal -- but there are major changes in storage and notifier (which has been split in 3), so it'll be quite a bit of work.
