### ISSUE TITLE
Drop Python < 3.5 support

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/pynetworktables#54]
I would like to propose we drop support for Python 3.3 in 2019.

Python 3.3 is already EOL (as of September 2017), and is not distributed by major, currently supported GNU/Linux distros, so I don't anticipate this being a problem for any team.

We've already announced on CD that pynetworktables will continue to support Python 3.3 for this year, so I guess we're keeping it this way.  I wouldn't imagine we'd have many more changes this year, so this probably won't be much of a problem for us anyway.

**Comment by virtuald** [comment]
People use pynetworktables on weird embedded devices that may not have been updated in forever. I don't think we should drop support until there's a good reason to -- and it'll probably be dropped around the same time as Python 2.7 support...

**Comment by auscompgeek** [comment]
It'd be good to see the PyPI download stats, I guess.

**Comment by virtuald** [comment]
FWIW, it seems that 12 people on CD would like to drop Python 2 support. https://www.chiefdelphi.com/forums/showthread.php?p=1766160

**Comment by auscompgeek** [comment]
From what I can tell, upstream ntcore is being rearchitected to use an event loop.

We've also been talking about potentially internally using asyncio instead of threads, hopefully improving performance in the process. If we were to go down that path, we'd likely want to be able to use async/await syntax, which would mean dropping support for all Python versions before 3.5.

If anyone cares about Python 3.4 support (or if you _really_ care about Python 3.3), please speak up now.

**Comment by virtuald** [comment]
We will no longer support python < 3.5 in 2019.
